package network.packet

enum class PacketType {
    UNKNOWN, GENERIC,
    CLIENT_HANDSHAKE, SERVER_HANDSHAKE,
    REQUEST_LEVEL_INFO, LEVEL_INFO,
    REQUEST_LEVEL_DATA, LEVEL_DATA,
    REQUEST_CHUNK_DATA, CHUNK_DATA,
    REQUEST_PLAYER_DATA, PLAYER_DATA,
    REQUEST_LOAD_GAME, LOAD_GAME,

    PLAYER_ACTION,
    ACK_PLAYER_ACTION,

    UPDATE_BLOCK,
    LEVEL_UPDATE,

    LEVEL_LOADED_SUCCESS
}