package network.packet

enum class PacketType {
    UNKNOWN, GENERIC, CLIENT_HANDSHAKE, SERVER_HANDSHAKE, REQUEST_LEVEL_INFO, LEVEL_INFO, REQUEST_LEVEL_DATA, LEVEL_DATA,

    REQUEST_CHUNK_DATA, CHUNK_DATA,

    ADD_BLOCK_TO_LEVEL,

    REQUEST_JOIN_LEVEL,

    ACCEPT_JOIN_LEVEL,

    REQUEST_PLAYER_DATA,

    PLAYER_DATA,
    REMOVE_BLOCK,
    GIVE_ITEM,
    UPDATE_BLOCK,
    LOAD_GAME,
    REQUEST_LOAD_GAME,
    ACK_LEVEL_MODIFICATION,
    ADD_MOVING_TO_LEVEL
}