package io

enum class Control {
    CAMERA_UP, CAMERA_DOWN, CAMERA_LEFT, CAMERA_RIGHT, TOGGLE_INVENTORY,

    INTERACT, SHIFT_INTERACT, CONTROL_INTERACT, ALT_INTERACT, SCROLL_UP, SCROLL_DOWN, SECONDARY_INTERACT, SHIFT_SECONDARY_INTERACT, CONTROL_SECONDARY_INTERACT, ALT_SECONDARY_INTERACT,

    PLACE_BLOCK,
    SPAWN_ENTITY,
    SELECT_ENTITY_COMMAND,
    USE_ENTITY_COMMAND,
    START_SELECTION_ALL_OBJECTS, START_SELECTION_BLOCKS_ONLY, START_SELECTION_MOVING_ONLY,
    REMOVE_SELECTED_BLOCKS,
    TELEPORT,
    EDIT_RESOURCE_NODE,

    ESCAPE, DELETE,

    CURSOR_UP, CURSOR_DOWN, CURSOR_LEFT, CURSOR_RIGHT, SUBMIT, SELECT_UP, SELECT_DOWN, SELECT_LEFT, SELECT_RIGHT,
    COPY_TO_CLIPBOARD,
    CUT_TO_CLIPBOARD,
    PASTE_FROM_CLIPBOARD,

    /* Debug */
    TURN_OFF_DEBUG_INFO,
    POSITION_INFO,
    RENDER_HITBOXES,
    CHUNK_INFO,
    TUBE_INFO,
    PIPE_INFO,
    SCREEN_INFO,
    RESOURCE_NODES_INFO,

    /* Hotbar slots */
    SLOT_1,
    SLOT_2, SLOT_3, SLOT_4, SLOT_5, SLOT_6, SLOT_7, SLOT_8,

    TAKE_SCREENSHOT,

    TOGGLE_VIEW_CONTROLS,
    TOGGLE_MOVEMENT_TOOLS,

    GIVE_TEST_ITEM,
    DROP_HELD_ITEM,
    ROTATE_BLOCK,
    PICK_UP_DROPPED_ITEMS;

    enum class Group(vararg val controls: Control) {
        /* GUI clicks/scrolls, level clicks, etc */
        INTERACTION(INTERACT, SHIFT_INTERACT, CONTROL_INTERACT, ALT_INTERACT, SCROLL_UP, SCROLL_DOWN, SECONDARY_INTERACT, SHIFT_SECONDARY_INTERACT, CONTROL_SECONDARY_INTERACT, ALT_SECONDARY_INTERACT),

        DEBUG(POSITION_INFO, SCREEN_INFO, RESOURCE_NODES_INFO, CHUNK_INFO, TUBE_INFO, RENDER_HITBOXES, TURN_OFF_DEBUG_INFO),

        HOTBAR_SLOTS(SLOT_1, SLOT_2, SLOT_3, SLOT_4, SLOT_5, SLOT_6, SLOT_7, SLOT_8),

        AVAILABLE_IN_TEXT_EDITOR(ESCAPE, CURSOR_UP, CURSOR_DOWN, CURSOR_LEFT, CURSOR_RIGHT, SUBMIT, SELECT_UP, SELECT_DOWN, SELECT_LEFT, SELECT_RIGHT,
                COPY_TO_CLIPBOARD,
                CUT_TO_CLIPBOARD,
                PASTE_FROM_CLIPBOARD, TAKE_SCREENSHOT, DELETE),

        SELECTOR_TOOLS(START_SELECTION_ALL_OBJECTS, START_SELECTION_BLOCKS_ONLY, START_SELECTION_MOVING_ONLY),

        CAMERA(CAMERA_UP, CAMERA_DOWN, CAMERA_LEFT, CAMERA_RIGHT),

        SCROLL(SCROLL_DOWN, SCROLL_UP);

        operator fun contains(c: Control): Boolean = controls.contains(c)

        override fun toString(): String {
            return controls.joinToString()
        }
    }

}

